In [20]:
# Importing the libraries 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 

In [21]:
# Importing the database 
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [22]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [23]:
X = dataset.iloc[:, 3:13].values # Gender to EstimatedSalary
Y = dataset.iloc[:, 13].values # Exited
print(X)
print(Y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder 
# X: int obj obj int int float int int int float
labelencoder_X_1=LabelEncoder() 
X[:,1] = labelencoder_X_1.fit_transform(X[:,1]) 
labelencoder_X_2=LabelEncoder() 
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2]) 

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(columnTransformer.fit_transform(X), dtype = np.float64)
X = X[:, 1:]
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [26]:
#Splitting the dataset into the Training set and the Test Set 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)


StandardScaler removes the mean and scales each feature/variable to unit variance. This operation is performed feature-wise in an independent way. StandardScaler can be influenced by outliers (if they exist in the dataset) since it involves the estimation of the empirical mean and standard deviation of each feature.

In [27]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test)

In [28]:
# Importing the Keras libraries and packages 
import keras 
from keras.models import Sequential 
from keras.layers import Dense

In [35]:
model = Sequential([
    Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11),
    Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'),
    Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid')
])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 6)                 72        
                                                                 
 dense_4 (Dense)             (None, 6)                 42        
                                                                 
 dense_5 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [39]:
model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam', 
              metrics = ['accuracy']
            )

In [40]:
model.fit(X_train, y_train, batch_size = 10, epochs = 50)

Epoch 1/50
800/800 [==============================] - 13s 13ms/step - loss: 0.4802 - accuracy: 0.8039
Epoch 2/50
800/800 [==============================] - 3s 3ms/step - loss: 0.4026 - accuracy: 0.8311
Epoch 3/50
800/800 [==============================] - 5s 6ms/step - loss: 0.3886 - accuracy: 0.8329
Epoch 4/50
800/800 [==============================] - 3s 3ms/step - loss: 0.3796 - accuracy: 0.8351
Epoch 5/50
800/800 [==============================] - 6s 7ms/step - loss: 0.3728 - accuracy: 0.8379
Epoch 6/50
800/800 [==============================] - 3s 4ms/step - loss: 0.3682 - accuracy: 0.8438
Epoch 7/50
800/800 [==============================] - 3s 4ms/step - loss: 0.3632 - accuracy: 0.8526
Epoch 8/50
800/800 [==============================] - 3s 3ms/step - loss: 0.3603 - accuracy: 0.8545
Epoch 9/50
800/800 [==============================] - 3s 4ms/step - loss: 0.3568 - accuracy: 0.8541
Epoch 10/50
800/800 [==============================] - 2s 2ms/step - loss: 0.3553 - accuracy: 0.85

In [41]:
# Predicting the Test set results 
y_pred = model.predict(X_test) 
y_pred = (y_pred > 0.5)
print('y_pred',y_pred)
new_prediction = model.predict(sc.transform (
    np.array([[0.0, 0, 500, 1, 40, 3, 50000, 2, 1, 1, 40000]])
    ))
new_prediction = (new_prediction > 0.5)
print('new_prediction',new_prediction)

y_pred [[ True]
 [False]
 [False]
 ...
 [False]
 [ True]
 [ True]]
new_prediction [[False]]


In [42]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred) 
print (cm)

[[1471   98]
 [ 211  220]]
